# # Cloud Build configuration for Research Copilot
# # This file is used by: gcloud builds submit

# steps:
#   # Build the Docker image
#   - name: 'gcr.io/cloud-builders/docker'
#     args:
#       - 'build'
#       - '-f'
#       - 'deployment/Dockerfile.gcp'
#       - '--build-arg'
#       - 'HF_TOKEN=${_HF_TOKEN}'
#       - '-t'
#       - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${BUILD_ID}'
#       - '-t'
#       - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:latest'
#       - '.'

#   # Push the image to Artifact Registry
#   - name: 'gcr.io/cloud-builders/docker'
#     args:
#       - 'push'
#       - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${BUILD_ID}'

#   - name: 'gcr.io/cloud-builders/docker'
#     args:
#       - 'push'
#       - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:latest'

# # Substitutions (can be overridden via --substitutions flag)
# substitutions:
#   _REGION: 'us-central1'
#   _REPO_NAME: 'research-copilot'
#   _SERVICE_NAME: 'research-copilot'
#   _HF_TOKEN: ''  # Hugging Face token for authenticated downloads (set via --substitutions)

# # Build options
# options:
#   logging: CLOUD_LOGGING_ONLY
#   machineType: 'E2_HIGHCPU_8'  # Faster builds

# # Images to push (redundant with steps above, but ensures they're recorded)
# images:
#   - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${BUILD_ID}'
#   - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:latest'

# # Timeout for the build (default is 10 minutes, we need more for large images)
# timeout: '1800s'  # 30 minutes

# Cloud Build configuration for Research Copilot
# Securely injects HF_TOKEN from Secret Manager (no --substitutions needed)
# Builds with deployment/Dockerfile.gcp and pushes to Artifact Registry

steps:
  # Build the Docker image (HF_TOKEN comes from Secret Manager)
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    secretEnv: ["HF_TOKEN"]
    args:
      - "-c"
      - |
        set -euo pipefail

        IMAGE_BASE="${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}"

        echo "Building images:"
        echo "  ${IMAGE_BASE}:${BUILD_ID}"
        echo "  ${IMAGE_BASE}:latest"

        # Pass HF_TOKEN to Docker build as build-arg.
        # Use $$HF_TOKEN so Cloud Build doesn't try to substitute it before runtime.
        docker build \
          -f deployment/Dockerfile.gcp \
          --build-arg HF_TOKEN="$$HF_TOKEN" \
          -t "${IMAGE_BASE}:${BUILD_ID}" \
          -t "${IMAGE_BASE}:latest" \
          .

  # Push the image to Artifact Registry (BUILD_ID tag)
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${BUILD_ID}"

  # Push the image to Artifact Registry (latest tag)
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:latest"

# Pull HF_TOKEN from Secret Manager into env var HF_TOKEN for steps that declare secretEnv
availableSecrets:
  secretManager:
    - versionName: "projects/${PROJECT_ID}/secrets/HF_TOKEN/versions/latest"
      env: "HF_TOKEN"

# Substitutions (region/repo/service only; HF token is NOT a substitution anymore)
substitutions:
  _REGION: "us-central1"
  _REPO_NAME: "research-copilot"
  _SERVICE_NAME: "research-copilot"

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"

# Images recorded in the build
images:
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${BUILD_ID}"
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:latest"

# Timeout for the build
timeout: "1800s"

